[project]
name = "challan-pdf-genertor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.104.1",
    "pydantic==2.5.0",
    "pypdf2==3.0.1",
    "reportlab==4.0.7",
    "uvicorn[standard]==0.24.0",
]
